### ISSUE TITLE
Conver Funds method is not set to POST

### ISSUE THREAD

**Issue by jefjabs** [IonicaBizau/coins-ph#12]
Hi,
Been using your nodejs library for a while now, I just noticed that convertFunds method in nodejs library is not set POST, therefore, it will use GET request. According your documentation, to convert funds, you must use crypto-exchanges endpoint with sufficient data using "POST" to be able to execute this transaction which is also the case on my tests.
Cheers!

**Comment by IonicaBizau** [comment]
Thanks for that! ✨

**Comment by IonicaBizau** [comment]
Fixed via #13 and #11
