### ISSUE TITLE
sell order returns 404 not found

### ISSUE THREAD

**Issue by imjeffparedes** [IonicaBizau/coins-ph#22]
OS: El Capitan
NodeJs Version: 8.12.0
Error : 404 Not Found HTML Response Body from sellorder request
Expected Response: json containing the details of the order
Actual: HTML data rendered to 404 Page Not Found
Actual Result ScreenShot:  https://i.imgur.com/WGGQcKb.png

Code: 
```
var Coins = require("coins-ph")
let client = new Coins({
    key: ''
  , secret: ''

    // This is optional
  , host: process.env.COINS_HOST || "https://coins.ph/"
});
client.sellorder({sellorder_id: '4dbf5b20'}, (err, data) => {
    console.log(err || data);
})
```

**Comment by imjeffparedes** [comment]
Ok this is due to trailing slash at the end of url
`url = this.host + version + "/" + _url + "/" + (qs ? "?" + qs : "")`

**Comment by IonicaBizau** [comment]
Thanks! 😅

**Comment by iceniveth** [comment]
Will this be in v1.1.13?

I tried to make the change #22 on v1.1.12, it seems to break the cryptoAccounts, and payinOutlets.

**Comment by imjeffparedes** [comment]
@iceniveth  yes it affected other request as well. 
I found out that sell order url is not similar to other url. 
We have to create a catch which determine if the request is sell order and remove the trailing slash.
Thats what I did for now. Need new pull request.

**Comment by iceniveth** [comment]
How about we add another property on the option parameter of _request. Something like this:
![image](https://user-images.githubusercontent.com/16744414/49384400-df927b80-f755-11e8-8a6f-c9373b85612f.png)

And then on the createSellorder and for other URL that doesn't need '/':
![image](https://user-images.githubusercontent.com/16744414/49384453-fc2eb380-f755-11e8-9db8-0f2ca6dc0d12.png)

**Comment by IonicaBizau** [comment]
What I don’t understand is: why does an endpoint need a slash and the other one no?

An option could work.

**Comment by iceniveth** [comment]
sellorder wasn't working
`GET https://coins.ph/api/v2/sellorder/4dbf5b20/?sellorder_id=4dbf5b20`

#23 was merge to fix it but broke other endpoints:
`GET https://coins.ph/d/api/payin-outlets?region=PH`
`GET https://coins.ph/api/v3/crypto-accounts?currency=PBTC`

Should have some way to omit `/` to some endpoints like the `sellorder` 🤔

**Comment by IonicaBizau** [comment]
Ah, perhaps because they are different API versions.

We could add an option, like you mentioned.
