### ISSUE TITLE
Add endpoints for payout outlet

### ISSUE THREAD

**Issue by iceniveth** [IonicaBizau/coins-ph#34]
Hello @IonicaBizau, I would like to add these methods:

- payout-outlets
- payout-outlet-categories
- payout-outlet-fees

![image](https://user-images.githubusercontent.com/16744414/49737941-0bb77a80-fcc9-11e8-802a-66c561490aa6.png)

😀

**Comment by IonicaBizau** [comment]
That would be great! ✨

**Comment by iceniveth** [comment]
#35
