### ISSUE TITLE
POST requests return error

### ISSUE THREAD

**Issue by mmikrut** [IonicaBizau/coins-ph#39]
Hi,
I'm testing a simple implementation using coins-ph for transfers and payments.
All GET callbacks work, but any callback using POST returns errors:

For example below is what is being sent (I added console log  statement inside of _request function)

> SENDING: { url: 'https://coins.ph/api/v3/transfers/', method: 'POST', headers: { ACCESS_SIGNATURE: '201abac281 ....... a48e3d2e09b3', ACCESS_KEY: 'A2yoVgU0wSRYQO6HY6 ....... msdItFWGzZe4hA', ACCESS_NONCE: '1.5687754773069998e+262' }, json: { target_address: 'mm......@gmail.com', account: '5a826b0e4 ........   c2695ec8fae', amount: 10.01, message: 'test transfer from bookme c1wallet' } }

and response from server (Again hacked the error code to display error, BTW the error returned from coins.ph is not an array anymore but an object, so current code fails to extract error text).

> Error: {"verification_code":["Please update your app to make this transaction."]}\n    at Request._callback (/srv/local_modules/coins-ph/lib/index.js:622:27)\n    at Request.self.callback (/srv/node_modules/request/request.js:185:22)\n    at emitTwo (events.js:126:13)\n    at Request.emit (events.js:214:7)\n    at Request.<anonymous> (/srv/node_modules/request/request.js:1161:10)\n    at emitOne (events.js:116:13)\n    at Request.emit (events.js:211:7)\n    at IncomingMessage.<anonymous> (/srv/node_modules/request/request.js:1083:12)\n    at Object.onceWrapper (events.js:313:30)\n    at emitNone (events.js:111:20)'

**Comment by IonicaBizau** [comment]
I would recommend writing to support regarding this.
