### ISSUE TITLE
i found a problem on createPaymentRequest but i managed to edit the code u might want to check it

### ISSUE THREAD

**Issue by william-levi** [IonicaBizau/coins-ph#9]

**Comment by IonicaBizau** [comment]
Can you create a pull request, please and explain the changes? Thanks!

**Comment by william-levi** [comment]
you created two "createPaymentRequest" on index.js one with url: "transfer" and the other with "payment-request". So , i erase the one with transfer url. then i managed to successfully create a paymentRequest.

**Comment by IonicaBizau** [comment]
Oh, thank you very much for this point! Gonna fix it!

**Comment by william-levi** [comment]
thanks for this.. it makes my work easy. :D

**Comment by IonicaBizau** [comment]
😄
